name: Release & Deploy
on:
  workflow_run:
    workflows: ["Manual Release"]
    types:
      - completed
  push:
    tags:
      - "release-v*"

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: main

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          server-id: 'github'

      - name: Extract tag info
        id: tags
        run: |
          CURRENT_TAG=${GITHUB_REF_NAME}
          CURRENT_VER=$(echo "$CURRENT_TAG" | sed 's/release-v//')
          [ -z "$CURRENT_VER" ] && CURRENT_VER="unknown"
      
          echo "CURRENT_VERSION=$CURRENT_VER" >> $GITHUB_OUTPUT
          echo "name=JIssueSystem Library v$CURRENT_VER" >> $GITHUB_OUTPUT

      - name: Build JAR
        run: |
          mvn -B clean install -DskipTests
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Package Artifact
        run: |
          mkdir -p dist
          CURRENT_VERSION=${{ steps.tags.outputs.CURRENT_VERSION }}
          cp target/jissuesystem-*.jar dist/

      - name: Set Maven version
        run: mvn versions:set -DnewVersion=${{ steps.tags.outputs.CURRENT_VERSION }}

      - name: Deploy
        run: |
          mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create Release & Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/*
          append_body: true
          make_latest: true
          name: ${{ steps.tags.outputs.name }}
          generate_release_notes: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
